- name: Write {{app_name}} service.
  template: 
    src: "{{prod_dir}}roles/common/templates/systemd.j2"
    dest: /etc/systemd/system/{{app_name}}.service
  become: true


- name: Enable {{app_name}} service on boot and reload daemon.
  systemd: 
    name: "{{app_name}}"
    enabled: yes
    daemon_reload: yes
  become: true

- name: Restart {{app_name}} service.
  service:
    name: "{{app_name}}"
    state: restarted
  become: true
